name: TodoCopilot Project

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: <YOUR_AZURE_CONTAINER_REGISTRY>.azurecr.io
        username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t <YOUR_AZURE_CONTAINER_REGISTRY>.azurecr.io/<YOUR_IMAGE_NAME>:latest .
        docker push <YOUR_AZURE_CONTAINER_REGISTRY>.azurecr.io/<YOUR_IMAGE_NAME>:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: <YOUR_AZURE_WEB_APP_NAME>
        images: <YOUR_AZURE_CONTAINER_REGISTRY>.azurecr.io/<YOUR_IMAGE_NAME>:latest
        slot-name: production