name: TodoCopilot Project

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}.azurecr.io/todocopilot:latest .
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}.azurecr.io/todocopilot:latest

    - name: Deploying to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEB_APP_NAME }}
        images: ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/todocopilot:latest
        slot-name: production